
modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'LGPL-3.0-or-later'
showAsResourcePack = false
mods = [
    { modId = 'more_heads', version = '__VERSION__', displayName = 'More Heads', description = 'Adds survival-friendly access to mob and player heads with intentional hoe-based drops, avoiding farm pollution and preserving vanilla progression.', logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/IDVPmSM5/forge_updates.json', authors = 'nwrenger', displayURL = 'https://modrinth.com/datapack/more-heads' },
]
issueTrackerURL = 'https://github.com/nwrenger/more-heads/issues'
